import test from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';import handler from '../api/school.js';
process.env.SUPABASE_URL='https://example.supabase.co';process.env.SUPABASE_SERVICE_ROLE_KEY='test';process.env.SESSION_SECRET='x'.repeat(64);process.env.APP_ORIGIN='https://school.example';
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
const row=(n,kind,data)=>({id:id(n),kind,data,version:1,created_at:'2026-09-01T00:00:00Z'});
async function environment(fn){let records=[row(1,'profile',{name:'Principal',role:'principal',authId:'p'}),row(2,'profile',{name:'Teacher',role:'teacher',department:'Physics',authId:'t'}),row(3,'profile',{name:'HOD',role:'hod',department:'Physics',authId:'h'}),row(4,'student',{name:'Student',class:'Form 5A',matricule:'TEST001',subjects:[],gender:'Male'}),row(5,'classroom',{name:'Form 5A',subjects:['Physics']}),row(6,'assignment',{teacherId:id(2),class:'Form 5A',subject:'Physics',department:'Physics'})];const original=globalThis.fetch;let next=20;
 globalThis.fetch=async(url,opts={})=>{const u=new URL(url);if(u.pathname==='/auth/v1/user')return Response.json({id:'verified'});if(u.pathname.endsWith('/rpc/school_save_record')){const b=JSON.parse(opts.body);let r=records.find(r=>r.id===b.record_id);if(r){if(r.version!==b.expected_version)return Response.json({code:'40001'},{status:409});r.data=b.record_data;r.version++;}else{r=row(next++,b.record_kind,b.record_data);records.push(r);}return Response.json([r]);}if(!u.pathname.endsWith('/school_records'))throw Error('Unexpected mock path '+u.pathname);let found=records.filter(r=>{for(const [k,v] of u.searchParams){if(['select','order','limit','offset'].includes(k))continue;const value=k==='kind'?r.kind:k==='id'?r.id:k.startsWith('data->>')?r.data[k.slice(7)]:null;if(v.startsWith('eq.')&&String(value)!==v.slice(3))return false;if(v.startsWith('in.(')&&!v.slice(4,-1).split(',').includes(value))return false;if(v.startsWith('gte.')&&String(value||'')<v.slice(4))return false;}return true;});const offset=Number(u.searchParams.get('offset')||0);return Response.json(found.slice(offset,offset+Number(u.searchParams.get('limit')||1000)));};
 const call=async(actor,body)=>{const payload=actor==='student'?{studentId:id(4)}:{authId:actor,accessToken:'test-token'};const data=Buffer.from(JSON.stringify({...payload,exp:Date.now()+3600000})).toString('base64url');const sig=crypto.createHmac('sha256',process.env.SESSION_SECRET).update(data).digest('base64url');let status=200,value;await handler({method:'POST',headers:{origin:process.env.APP_ORIGIN,cookie:`school_session=${data}.${sig}`},body},{setHeader(){},status(n){status=n;return this},json(v){value=v;return this}});return {status,value};};
 try{await fn({records,call});}finally{globalThis.fetch=original;}}
test('teacher upload approval and timed exam run through API without exposing answer key',()=>environment(async({records,call})=>{const data={title:'Physics test',class:'Form 5A',subject:'Physics',department:'Physics',type:'test',submissionMode:'online',status:'pending',durationMinutes:10,questions:[{type:'mcq',prompt:'Select one',options:['A','B'],correct:1,points:2}]};let a=await call('t',{op:'save',kind:'resource',data});assert.equal(a.status,200,JSON.stringify(a));const resource=a.value.row;let denied=await call('student',{op:'exam-start',resourceId:resource.id});assert.equal(denied.status,403);a=await call('h',{op:'save',kind:'resource',id:resource.id,version:resource.version,data:{...resource.data,status:'published'}});assert.equal(a.status,200,JSON.stringify(a));a=await call('student',{op:'exam-start',resourceId:resource.id});assert.equal(a.status,200);assert.equal('correct' in a.value.row.data.questions[0],false);const deadline=a.value.row.data.deadline;a=await call('student',{op:'exam-start',resourceId:resource.id});assert.equal(a.value.row.data.deadline,deadline);a=await call('student',{op:'exam-submit',resourceId:resource.id,answers:{'1':'1'}});assert.equal(a.value.row.data.autoScore,2);assert.equal(a.value.row.data.status,'submitted');a=await call('student',{op:'exam-save',resourceId:resource.id,answers:{'1':'0'}});assert.notEqual(a.status,200);assert.equal(records.find(r=>r.kind==='exam_attempt').data.autoScore,2);}));
test('teacher request can be issued by principal but cannot be issued by teacher',()=>environment(async({call})=>{let a=await call('t',{op:'save',kind:'document_request',data:{requestType:'employment confirmation',purpose:'For my records'}});assert.equal(a.status,200,JSON.stringify(a));const request=a.value.row;const data={kind:'letter',requestId:request.id,recipient:'Teacher',principal:'Principal',title:'CONFIRMATION OF EMPLOYMENT',body:'Confirmed school employment.',reference:'TEST-001',issueDate:'2026-09-09'};a=await call('t',{op:'save',kind:'document',data});assert.equal(a.status,403);a=await call('p',{op:'save',kind:'document',data});assert.equal(a.status,200,JSON.stringify(a));assert.equal(a.value.row.data.profileId,id(2));assert.equal(a.value.row.data.token.length,48);a=await call('t',{op:'save',kind:'document_request',id:request.id,version:request.version,data:{...request.data,status:'cancelled'}});assert.notEqual(a.status,200);}));
test('wrong department and fake PDF uploads are rejected by server',()=>environment(async({call})=>{const data={title:'Notes',class:'Form 5A',subject:'Chemistry',department:'Physics',type:'note',submissionMode:'in class',status:'pending',body:'Text'};let a=await call('t',{op:'save',kind:'resource',data});assert.equal(a.status,403);a=await call('t',{op:'save',kind:'resource',data:{...data,subject:'Physics',attachment:{name:'bad.pdf',data:'data:application/pdf;base64,aGVsbG8='}}});assert.equal(a.status,400);}));
