export const subjectCatalogue=[
 ['English Language','English','shared'],['French','French','shared'],['Mathematics','Mathematics','shared'],['Additional Mathematics','Mathematics','science'],['Biology','Biology','science'],['Chemistry','Chemistry','science'],['Citizenship','History','shared'],['Commerce','Economics','arts'],['Computer Science','Computer Science','shared'],['Economics','Economics','arts'],['Geography','Geography','arts'],['Geology','Geography','science'],['History','History','arts'],['Human Biology','Biology','science'],['Logic','Logic','arts'],['Physics','Physics','science'],['Food and Nutrition','Food and Nutrition','elective'],['Literature in English','English','arts'],['Physical Education','Physical Education','shared'],['Religious Studies','Religious Studies','elective'],['Manual Labour','Physical Education','shared'],['Philosophy','Philosophy','arts']
].map(([name,department,group])=>({name,department,group,coefficient:1}));
export function classSubjects(cls,all){const rule=all.find(r=>r.kind==='classroom'&&r.data.name===cls);return rule?rule.data.subjects||[]:null;}
export function enrolment(student,all){const compulsory=classSubjects(student.class,all);return compulsory===null?student:{...student,requiredSubjects:compulsory};}
export function availableSubjects(all){const map=new Map(subjectCatalogue.map(s=>[s.name,s]));for(const r of all.filter(r=>r.kind==='subject'))map.set(r.data.name,r.data);return [...map.values()];}
export function recommendSubjects(stream){const shared=['English Language','French','Mathematics','Computer Science','Citizenship','Physical Education','Manual Labour'];if(stream==='Arts')return [...shared,'History','Geography','Economics','Literature in English','Commerce'];if(stream==='Science')return [...shared,'Physics','Chemistry','Biology'];return [...shared,'History','Geography','Biology','Physics','Chemistry'];}
export function academicYear(date=new Date()){const n=date.getUTCFullYear()-(date.getUTCMonth()<8?1:0);return n+'/'+(n+1);}
export function competency(mark){if(mark===null||mark===undefined)return '';return mark>=18?'A+/E':mark>=15?'CA':mark>=11?'CECA':'CNA';}
