import QRCode from 'qrcode';
import {documentTitles,documentLines,letterheadEN,letterheadFR,displayDate} from './document-layout.js';
export {letterheadEN,letterheadFR};export const titles=documentTitles;
export const bytesToBase64=bytes=>{let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s);};
export function exportModel(d,origin){if(d.kind==='letter')return {...d,title:d.title||'School message',body:d.body,...(d.token?{url:origin+'/verify/'+d.token}:{})};if(!titles[d.kind]||!d.token)throw Error('Choose a registered attestation.');return {...d,title:titles[d.kind],lines:documentLines(d),url:origin+'/verify/'+d.token};}
export async function loadExportAssets(){const paths={crest:'/crest.jpg',font:'/fonts/Tinos-Regular.ttf',bold:'/fonts/Tinos-Bold.ttf'};const entries=await Promise.all(Object.entries(paths).map(async([k,path])=>{const r=await fetch(path);if(!r.ok)throw Error('A bundled document asset failed to load. Refresh and try again.');return [k,new Uint8Array(await r.arrayBuffer())];}));return Object.fromEntries(entries);}
export async function makeDocx(models,assets){const {Document,Packer,Paragraph,TextRun,ImageRun,Table,TableRow,TableCell,WidthType,AlignmentType,BorderStyle}=await import('docx');
 const run=(text,bold=false,size=22)=>new TextRun({text:String(text||''),font:bold?'Tinos Bold':'Tinos',size,bold});
 const para=(text,options={})=>new Paragraph({children:[run(text)],spacing:{after:120,line:260},...options});
 const border={style:BorderStyle.NONE,size:0,color:'FFFFFF'},borders={top:border,bottom:border,left:border,right:border};const sections=[];
 for(const d of models){const cell=(lines,w)=>new TableCell({width:{size:w,type:WidthType.DXA},borders,children:lines.map((s,i)=>new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:0,line:200},children:[run(s,i!==1,18)]}))});
 const head=new Table({width:{size:9600,type:WidthType.DXA},columnWidths:[4250,1100,4250],rows:[new TableRow({children:[cell(letterheadEN,4250),new TableCell({borders,width:{size:1100,type:WidthType.DXA},children:[new Paragraph({alignment:AlignmentType.CENTER,children:[new ImageRun({type:'jpg',data:assets.crest,transformation:{width:55,height:60}})]})]}),cell(letterheadFR,4250)]})]});
 const children=[head,para('Reg. No. 6CE1GSAD110491113',{spacing:{before:160,after:40},border:{top:{style:BorderStyle.SINGLE,size:4,color:'555555'}}}),para(`Ref. No. ${d.reference||''}                    LIMBE, ${displayDate(d.issueDate)}`,{spacing:{after:240}}),new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:260},children:[new TextRun({text:d.title,font:'Tinos',bold:true,underline:{},size:24})]})];
 if(d.year)children.push(para('ACADEMIC YEAR '+d.year,{alignment:AlignmentType.CENTER,spacing:{after:240}}));if(d.status==='revoked')children.push(para('REVOKED / RÉVOQUÉ'));
 if(d.lines)for(const line of d.lines){children.push(new Paragraph({keepNext:true,spacing:{before:170,after:0,line:260},children:[run(line.en),run(line.value,true),run(line.tail||'')]}),new Paragraph({spacing:{after:130,line:220},children:[run(line.fr,false,18)]}));}
 else for(const text of String(d.body).split('\n'))children.push(para(text));
 children.push(para('THE PRINCIPAL / LE PROVISEUR',{alignment:AlignmentType.RIGHT,spacing:{before:250,after:600}}),para(d.principal||'',{alignment:AlignmentType.RIGHT}));
 if(d.url){const qr=await QRCode.toDataURL(d.url,{width:180,margin:1});children.push(new Paragraph({keepNext:true,spacing:{before:0,after:0},children:[new ImageRun({type:'png',data:Uint8Array.from(atob(qr.split(',')[1]),c=>c.charCodeAt(0)),transformation:{width:105,height:105}})]}),new Paragraph({spacing:{after:0},children:[run('Verify this document',false,14)]}));}
 sections.push({properties:{page:{size:{width:11906,height:16838},margin:{top:680,bottom:680,left:1000,right:1000}}},children});}
 return Packer.toBlob(new Document({fonts:[{name:'Tinos',data:assets.font},{name:'Tinos Bold',data:assets.bold}],creator:'GHS Mbonjo Limbe',styles:{default:{document:{run:{font:'Tinos',size:22}}}},sections}));}
export async function makePdf(models,assets){if(!assets.font||!assets.bold)throw Error('Bundled document fonts failed to load.');const {jsPDF}=await import('jspdf');const pdf=new jsPDF({unit:'mm',format:'a4',compress:true});for(const [key,style] of [['font','normal'],['bold','bold']]){pdf.addFileToVFS(style+'.ttf',bytesToBase64(assets[key]));pdf.addFont(style+'.ttf','Tinos',style);}let y=20;
 const text=(s,x,y,size=11,bold=false,opts={})=>{pdf.setFont('Tinos',bold?'bold':'normal');pdf.setFontSize(size);pdf.text(String(s||''),x,y,opts);};
 const paragraph=(s,size=11,bold=false)=>{pdf.setFont('Tinos',bold?'bold':'normal');pdf.setFontSize(size);for(const line of pdf.splitTextToSize(String(s),174)){if(y>271){pdf.addPage();y=20;}text(line,18,y,size,bold);y+=size*.43;}};
 for(let i=0;i<models.length;i++){const d=models[i];if(i)pdf.addPage();letterheadEN.forEach((s,n)=>text(s,54,15+n*3.4,9,n!==1,{align:'center',maxWidth:75}));letterheadFR.forEach((s,n)=>text(s,156,15+n*3.4,9,n!==1,{align:'center',maxWidth:75}));pdf.addImage(assets.crest,'JPEG',96,17,18,21);pdf.line(18,49,192,49);text('Reg. No. 6CE1GSAD110491113',18,54,9);text('Ref. No. '+(d.reference||''),18,60,9);text('LIMBE, '+displayDate(d.issueDate),192,60,9,false,{align:'right'});text(d.title,105,71,12,true,{align:'center'});pdf.setFont('Tinos','bold');pdf.setFontSize(12);const tw=pdf.getTextWidth(d.title);pdf.line(105-tw/2,72,105+tw/2,72);y=83;if(d.year){text('ACADEMIC YEAR '+d.year,192,y,10,false,{align:'right'});y+=10;}if(d.status==='revoked'){paragraph('REVOKED / RÉVOQUÉ');y+=3;}
 if(d.lines){for(const l of d.lines){pdf.setFontSize(11);let x=18;for(const [value,bold] of [[l.en,false],[l.value||'',true],[l.tail||'',false]]){pdf.setFont('Tinos',bold?'bold':'normal');for(const word of String(value).split(/(\s+)/)){const width=pdf.getTextWidth(word);if(x+width>192){x=18;y+=4.73;}text(word,x,y,11,bold);x+=width;}}y+=4.73;paragraph(l.fr,9);y+=6;}}
 else paragraph(d.body,11);
 if(y+54>274){pdf.addPage();y=20;}y+=4;text('THE PRINCIPAL / LE PROVISEUR',192,y,10,true,{align:'right'});text(d.principal||'',192,y+24,11,true,{align:'right'});
 if(d.url){const qr=await QRCode.toDataURL(d.url,{width:180,margin:1});pdf.addImage(qr,'PNG',18,y+6,28,28);text('Verify this document',32,y+37,8,false,{align:'center'});}}
 return pdf.output('blob');}
export function downloadBlob(blob,filename){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
